# This is static code scan check which get updated in the PR.

name: Static Code Scan Check

on:
  issue_comment:
    types: [created, edited]

jobs:
  Static_Code_Scan_By_PR:
  
    runs-on: [self-hosted]
    name: Static Code Scan Check
    if: ${{ github.event.issue.pull_request }}
    steps:
    # Checkout the repository content to github runner.
      - name: Check-out Repository
        uses: actions/checkout@v2
        with:
            repository: intel-innersource/applications.devops.isdm.onboarding-kit
            ref: main
            token: ${{ secrets.AUTH_TOKEN }}
            path: script
          
    # Running the static code script to check for comments in PR.
      - name: Getting Github Token & Running Script
        env:
            AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PULL_REQUEST_NUMBER : ${{ github.event.issue.number }}
            REPO_NAME : ${{ github.event.repository.name }}
            OWNER: ${{ github.event.repository.owner.login }}
        run: |
            cd script
            python3 code_scan.py --auth_token=$AUTH_TOKEN --pull_number=$PULL_REQUEST_NUMBER --repo_name=$REPO_NAME --repo_org=$OWNER
