name: Commit Check PRs

on: 
    pull_request:
        types: [opened, reopened, synchronize]

jobs:
  Commit_Check:
    name: PR Commit Checks
    runs-on: [self-hosted]
    
    steps:
    # Checkout commit-check Repository
    - name: Check-out Commit-Check Repo
      uses: actions/checkout@v1
    
    # Checkout the repository content to github runner.
    - name: Check-out Onboarding Scripts
      uses: actions/checkout@v2
      with:
            repository: intel-innersource/applications.devops.isdm.onboarding-kit
            ref: main
            token: ${{ secrets.AUTH_TOKEN }}
            path: script
    
    # Running commit check script.
    - name: Run Script
      env:
            AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PULL_REQUEST_NUMBER : ${{ github.event.pull_request.number }}
            REPO_NAME : ${{ github.event.repository.name }}
            OWNER: ${{ github.event.repository.owner.login }}
      run: |
        git pull origin ${{ github.event.pull_request.base.ref }}
        mv script/commit-check.py .
        python3 commit-check.py ${{ github.event.pull_request.base.ref }}..${{ github.event.pull_request.head.sha }} --auth_token=$AUTH_TOKEN --pull_number=$PULL_REQUEST_NUMBER --repo_name=$REPO_NAME --repo_org=$OWNER
      shell: sh
